server_id: " "
activity: "Je suis dev par Panda_Guerrier !"
admin_roles:
  - ""
roles:
    join_role: ""
    admin_role: ""
    select_roles:
        - id: "role id"
          name: "role name"
          emoji: "ðŸ«”"
        - id: "role id2"
          name: "role name2"
          emoji: "ðŸ—‘"
channels:
  welcome: ""
  suggestion: ""


# mettez votre rÃ¨glement ici tout en entier, remplacez les sauts de lignes par des \n
rules: "Pas d'insultes\nPas de flood\nNe mentez pas !"
